name: CI - Maven & JUnit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: ['21']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Temurin Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build and run unit tests
        run: mvn -B --no-transfer-progress test

      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            target/surefire-reports/**
            target/*.dumpstream
          if-no-files-found: ignore
